### ISSUE TITLE
Pico2 w RP2350 CYW43 ISSUE

### ISSUE THREAD

**Issue by equaz0r** [pimoroni/unicorn#5]
Cannot get wireless working with release firmware even with reflashing on new Unicorn Galactic 2350 board. Trying examples like clock.py or cheerlights with appropriate dependencies in Thonny results in [CYW43] core not in reset and HT not ready - after lots of trying i have flashed with pimoroni-pico-rp2350 v0.0.11 and whilst the display obviously does not function - the wireless works ok using cheerlights example.  Discord suggests at least one other user with same new unicorn has same issue. Happy to provide any detail that helps.

**Comment by equaz0r** [comment]
(Just tried a flash from https://github.com/pimoroni/unicorn/actions/runs/12411899294 ) and same issue - using network_manager.py, WIFI_CONFIG.py and cheerlights.py example I get the below in Thonny :
>>> %run -c $EDITOR_CONTENT
[CYW43] core not in reset
[CYW43] core not in reset
[CYW43] core not in reset
[CYW43] HT not ready
[CYW43] Failed to start CYW43
[CYW43] Failed to start CYW43
Wifi connection failed! [Errno 1] EPERM
Traceback (most recent call last):
  File "<stdin>", line 58, in <module>
  File "requests/__init__.py", line 201, in get
  File "requests/__init__.py", line 79, in request
OSError: -6
Interestingly if I just hit run again, it locks up/no error messages and I have to reset the board to get a response.
(as per the above, the output when I ran cheerlights without the drawing function for the unicorn (commented out) and the network_manager.py example using the pico-rp2350 uf2 mentioned is :
Client None 0.0.0.0
Connecting to wifi...
Client None 0.0.0.0
Connecting to wifi...
Client None 0.0.0.0
Connecting to wifi...
Client None 0.0.0.0
Connecting to wifi...
Client None 0.0.0.0
Connecting to wifi...
Client None 0.0.0.0
Connecting to wifi...
Client True 192.168.0.64
Connecting to wifi...
Wifi connection successful!
(If a little slow)
So must definitely be something firmware related - will keep an eye on unicorn specific firmware for the w 2 - specific firmware I used from above that worked ok was:
pico2_w-v0.0.11-pimoroni-micropython.uf2

**Comment by djchadderton** [comment]
I'm getting similar errors from clock.py when I add the secrets.py file:

```
[CYW43] HT not ready
[CYW43] core not in reset
[CYW43] core not in reset
[CYW43] core not in reset
[CYW43] HT not ready
Traceback (most recent call last):
  File "<stdin>", line 215, in <module>
  File "<stdin>", line 123, in sync_time
OSError: [Errno 1] EPERM
```

It looks like the Pico 2 version was rushed out in time for Christmas before the firmware was working fully. I would have been happy with a fully working Pico 1 version if they had still been available.

**Comment by bmustill-rose** [comment]
I'm also experiencing the same issue. Interestingly, yesterday, after a few attempts of flashing 1.24.0 I was able to get WiFi working consistently having previously received the same errors as everyone else, but today I'm back to receiving the various CYW43 messages.

**Comment by Gadgetoid** [comment]
Sorry for the lack of response here, it's been a year... already... 😬

Since Wireless support has now been merged into MicroPython I'll try building a new release and see if that gets us anywhere!

**Comment by Gadgetoid** [comment]
Okay, try: https://github.com/pimoroni/unicorn/releases/tag/v1.24.1

**Comment by djchadderton** [comment]
Afraid not. Flashed it to the unicorn, loaded up clock.py which worked fine when still attached via USB, but when I added a secrets.py and tried again, I got the same:

```
MPY: soft reboot
[CYW43] HT not ready
[CYW43] core not in reset
[CYW43] core not in reset
[CYW43] core not in reset
[CYW43] HT not ready
Traceback (most recent call last):
  File "<stdin>", line 215, in <module>
  File "<stdin>", line 123, in sync_time
OSError: [Errno 1] EPERM
```

**Comment by Gadgetoid** [comment]
Ooof. I wonder if this is related to the RM2 wireless issues, or some other regression. I'm not actually sure that low level debug info should be visible at all, too.

Do you have any luck with: 

1. the vanilla MicroPython firmware - https://micropython.org/download/RPI_PICO2_W/
2. *just* doing WiFi, without running the screen at all

(Though 1 and 2 more or less amount to the same thing)

**Comment by djchadderton** [comment]
Did a test with MicroPython v1.25.0-preview.221.gc69f0e4ee and the wifi connected without errors.

**Comment by Gadgetoid** [comment]
I've a suspicion that our display code is upsetting wireless, since we've tackled similar problems with Presto. Why this is suddenly a problem *now* though, I'm unsure.

If you set up wireless before firing up the display, it may well work. Suffice to say I'm going to need to do some testing.

**Comment by Gadgetoid** [comment]
My suspicion is all but confirmed, and I've produced a pure MicroPython repro - which "fails successfully" on a vanilla Pico (no Unicorn hardware attached) running a vanilla MicroPython preview - and raised an issue upstream: https://github.com/micropython/micropython/issues/16627

This doesn't help us much in the interim, but setting up wireless *before* the display may still work.

This appears to be a regression from RP2040 behaviour and - I'm sure - from our earlier tests with Pico2 W.

**Comment by Gadgetoid** [comment]
Okay the builds here include a (very crude) workaround that should get things working while we figure out what's going on: https://github.com/pimoroni/unicorn/actions/runs/12947579998?pr=9

**Comment by djchadderton** [comment]
I tried last night a test script (Python isn't my first language, and I've only recently started playing with the 'W' flavour of Pico) and it worked to connect to Wi-Fi and then display "Hello World" on the Galactic Unicorn. But instead of exiting, Thonny's shell froze for a while and then threw an error, and I had to reset the Pico to reconnect.

I've just tried clock.py again after installing this new build and it did something similar. It displayed `MPY: soft reboot` in the shell, but nothing else appeared there or on the Unicorn. CTRL-C did nothing. The stop button in Thonny just produced a pink line across the shell display, then after resetting the Pico, it showed:

```
PROBLEM IN THONNY'S BACK-END: Internal error (serial.serialutil.SerialException: write failed: [Errno 6] Device not configured).
See Thonny's backend.log for more info.
You may need to press "Stop/Restart" or hard-reset your MicroPython device and try again.


Process ended with exit code 0.
```

I don't know if it's a problem with the build or with Thonny, but it ain't working!

**Comment by equaz0r** [comment]
Sorry - just seen all this after not paying attention - if it helps, I've just downloaded the galactic pico 2 (with filesystem) release from here:
https://github.com/pimoroni/unicorn/actions/runs/12966523239
Took a fresh copy of the clock.py example without any of the fiddling/changes I'd done previously during testing and success (i think - will re-run shortly with some code to echo IP address/connection details to confirm but):
5%%516:07 24/01/202516:024/01>>> %Run -c $EDITOR_CONTENT 'display.pressed(badger2040.BUTTON_A)'

MPY: soft reboot
waiting for connection...
0.9692842
waiting for connection...
0.9692966
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
0.9693092
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
0.9693218
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
0.9693344
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
0.9693469
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
0.9693594
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
0.9693719
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
0.9693844
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
0.969397
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
Connected
Time set
0.9694096
0.9694221

**Comment by equaz0r** [comment]
Confirm - succesful in getting IP details:
0.9760425
Connected
('192.168.0.64', '255.255.255.0', '192.168.0.1', '194.168.4.100')
Time set
0.9760314

**Comment by equaz0r** [comment]
Running without thonny after replacing (A) button with clock.py import. 

![image](https://github.com/user-attachments/assets/56e0cb34-1242-4b98-be88-55b7dc3bc1ca)

**Comment by djchadderton** [comment]
Just tried what @equaz0r described and it appears to be working for me now too!

**Comment by Gadgetoid** [comment]
This should be fixed with a backport as of 1.24.2 and properly when Pico SDK devel is released and updated in MicroPython.
